topologies:
  simple_topology: true

mount_preprocessing:
  enabled: true
  min_mount_distance: 5.0
  verbose: true

surface_separation:
  auto_split: true
  min_mounts_for_split: 2
  mounts_per_surface: 1
  split_along: 'auto'
  gap_width: 10
  verbose: true

design_exploration:
  single_bend: True
  double_bend : True

filter:
  Min Flange Width: True
  Min Bend Angle: False
  Tabs cover Rects: True
  Lines Cross: True
  Collisions: True
  Too thin segments: False

plot:
  Rectangles: True
  Tab Points: False
  Tabs: True
  Flanges: True
  Triangulate Tabs: True
  Corner Points: False
  
  Labels: False   # Turn off to increase plotting speed

  point_size: 30
  font_size: 30
  
  BP1_color: "red"
  BP2_color: "blue"
  FPA1_color: "green"
  FPA2_color: "green"
  FPB1_color: "orange"
  FPB2_color: "orange"